# -*- coding: utf-8 -*-
"""OpenCV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LMqtMb56vdxi121WC7f-3M5DTYIgdEbv
"""

!pip install opencv-python

!pip install matplotlib

import cv2 as cv
import matplotlib.pyplot as plt
import numpy as np
import os

def pureColors():
  zeros = np.zeros((100, 100))
  ones = np.ones((100, 100))

  bImg = cv.merge((zeros, zeros, 255*ones))
  rImg = cv.merge((255*ones, zeros, zeros))
  gImg = cv.merge((zeros, 255*ones, zeros))

  plt.figure()
  plt.subplot(231)
  plt.imshow(bImg)
  plt.title('blue')

  plt.subplot(232)
  plt.imshow(rImg)
  plt.title('red')

  plt.subplot(233)
  plt.imshow(gImg)
  plt.title('green')

  plt.show()

if __name__ == '__main__':
  pureColors()

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
from google.colab.patches import cv2_imshow

# This will prompt for authorization.
drive.mount('/content/drive')

# %cd /content/drive/MyDrive/

def readImg():

  path = '/content/drive/My Drive/cutePic1.jpg'
  img = cv.imread(path)
  cv2_imshow(img)
  cv.waitKey(0)

if __name__ == '__main__':
  readImg()

def readImgGrayScale():

  path = '/content/drive/My Drive/cutePic1.jpg'
  img = cv.imread(path)
  imgGray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
  cv2_imshow(imgGray)
  cv.waitKey(0)

if __name__ == '__main__':
  readImgGrayScale()

def hsvColorSegmenetation():

  path = '/content/drive/My Drive/cutePic1.jpg'
  img = cv.imread(path)
  imgRGB = cv.cvtColor(img, cv.COLOR_BGR2RGB)


  hsv = cv.cvtColor(img, cv.COLOR_BGR2HSV)
  lowerBound = np.array([0, 0, 50])
  upperBound = np.array([20, 180, 100])

  #plt.figure()
  #plt.imshow(imgRGB)
  #plt.show()

  mask = cv.inRange(hsv, lowerBound, upperBound)

  cv2_imshow(mask)

if __name__ == '__main__':
  hsvColorSegmenetation()

def imageResize():
  path = '/content/drive/My Drive/cutePic1.jpg'
  img = cv.imread(path)
  img = cv.cvtColor(img, cv.COLOR_BGR2RGB)

  #crop part of image
  img = img[350:420,  522:589, :]
  height,width,_ = img.shape

  scale_out = 1/4
  scale_in = 4

  interpMethods = [
      cv.INTER_AREA,
      cv.INTER_LINEAR,
      cv.INTER_NEAREST,
      cv.INTER_CUBIC,
      cv.INTER_LANCZOS4]


  interpTitles = ['area', 'linear', 'nearest', 'cubic', 'lanczos']

  plt.figure()
  plt.subplot(2,3,1)
  plt.imshow(img)

  for i in range(len(interpMethods)):
    plt.subplot(2,3,i+2)
    imgResize = cv.resize(img, (int(width*scale_in), int(height*scale_in)), interpolation=interpMethods[i])
    plt.imshow(imgResize)
    plt.title(interpTitles[i])
  plt.show()

if __name__ == '__main__':
  imageResize()

def grayHistogram():
  path = '/content/drive/My Drive/cutePic1.jpg'
  img = cv.imread(path, cv.IMREAD_GRAYSCALE)

  plt.figure()
  plt.imshow(img, cmap ='gray')

  hist = cv.calcHist([img], [0], None, [256], [0,256])
  plt.figure()
  plt.plot(hist)
  plt.xlabel('bins')
  plt.ylabel('# of pixels')
  plt.show()

def colorHistogram():
  path = '/content/drive/My Drive/cutePic1.jpg'
  img = cv.imread(path)
  imgRGB = cv.cvtColor(img, cv.COLOR_BGR2RGB)

  plt.figure()
  plt.imshow(imgRGB)

  colors = ['b', 'r', 'g']

  plt.figure()
  for i in range(len(colors)):
    hist = cv.calcHist([imgRGB], [i], None, [256], [0,256])

    plt.plot(hist, colors[i])
  plt.xlabel('pixel intensity')
  plt.ylabel('# of pixels')
  plt.show()

def histogramRegion():
  path = '/content/drive/My Drive/cutePic1.jpg'
  img = cv.imread(path)
  imgRGB = cv.cvtColor(img, cv.COLOR_BGR2RGB)
  imgRGB = imgRGB[650: 800, 650:850]

  plt.figure()
  plt.imshow(imgRGB)

  colors = ['b', 'r', 'g']

  plt.figure()
  for i in range(len(colors)):
    hist = cv.calcHist([imgRGB], [i], None, [256], [0,256])

    plt.plot(hist, colors[i])
  plt.xlabel('pixel intensity')
  plt.ylabel('# of pixels')
  plt.show()

if __name__ == '__main__':
  #grayHistogram()
  #colorHistogram()
  histogramRegion()

def convolution2d():
  path = '/content/drive/My Drive/cutePic1.jpg'
  img = cv.imread(path)
  imgRGB = cv.cvtColor(img, cv.COLOR_BGR2RGB)

  n = 100 #kernel size
  kernel = np.ones((n,n), np.float32) / (n*n) #calculate mean
  imgFilter = cv.filter2D(imgRGB, -1, kernel) #does convolution

  plt.figure()
  plt.subplot(121)
  plt.imshow(imgRGB)

  plt.subplot(122)
  plt.imshow(imgFilter)

  plt.show()

if __name__ == '__main__':
  convolution2d()

def callback (input):
  pass

def avgFiltering():
  path = '/content/drive/My Drive/cutePic1.jpg'
  img = cv.imread(path)

  winName = 'avg filter'
  cv.namedWindow(winName)
  cv.createTrackbar('n', winName, 0, 100, callback)

  height, width = img.shape
  scale = 1/4
  width = int(width*scale)
  height = int(height*scale)
  img = cv.resize(img, (width, height))

  while True:
    if cv.waitKey(1) == ord('q'):
      break

    n = cv.getTrackbarPos('n', winName)
    imgFilter = cv.blur(img, (n, n))
    cv2_imshow(imgFilter)

if __name__ == '__main__':
  avgFiltering()

def median():

  path = '/content/drive/My Drive/cutePic1.jpg'
  img = cv.imread(path)
  imgRGB = cv.cvtColor(img, cv.COLOR_BGR2RGB)

  #add noise to image
  noisyImg = imgRGB.copy()
  noiseProb = 0.05
  noise = np.random.rand(noisyImg.shape[0], noisyImg.shape[1])
  noisyImg[noise < noiseProb/2] = 0
  noisyImg[noise > 1-noiseProb/2] = 255

  imgFilter = cv.medianBlur(noisyImg, 5)

  plt.figure()
  plt.subplot(131)
  plt.imshow(imgRGB)

  plt.subplot(132)
  plt.imshow(noisyImg)

  plt.subplot(133)
  plt.imshow(imgFilter)

  plt.show()


if __name__ == '__main__':
  median()

def gaussianKernel(size, sigma):
  kernel = cv.getGaussianKernel(size, sigma)
  kernel = np.outer(kernel, kernel) #2d kernel
  return kernel


def guassianFiltering():
  path = '/content/drive/My Drive/cutePic1.jpg'
  img = cv.imread(path)

  n = 51 #kernel size

  fig = plt.figure()
  plt.subplot(121)
  kernel = gaussianKernel(n, 2)
  plt.imshow(kernel)

  ax = fig.add_subplot(122, projection = '3d')
  x = np.arange(0, n, 1)
  y = np.arange(0, n, 1)
  x, y = np.meshgrid(x, y)
  ax.plot_surface(x, y, kernel, cmap = 'viridis')
  plt.show()

if __name__ == '__main__':
  guassianFiltering()

def imageThresholding():
  path = '/content/drive/My Drive/cutePic1.jpg'
  img = cv.imread(path)
  imgGrayScale = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

  hist = cv.calcHist([imgGrayScale], [0], None, [256], [0,256])

  #plt.figure()
  #plt.plot(hist) #split peak between 200 - 250 ~ 225
  #plt.show() #

  threshOpts = [cv.THRESH_BINARY,
                cv.THRESH_BINARY_INV,
                cv.THRESH_TRUNC,
                cv.THRESH_TOZERO,
                cv.THRESH_TOZERO_INV]

  plt.figure()
  plt.subplot(231)
  plt.imshow(imgGrayScale, cmap = 'gray')

  for i in range(len(threshOpts)):
    plt.subplot(2,3,i+2)
    _, imgThresh = cv.threshold(imgGrayScale, 150, 255, threshOpts[i])
    plt.imshow(imgThresh, cmap = 'gray')
    plt.title(threshOpts[i])
  plt.show()


if __name__ == '__main__':
  imageThresholding()

def imageGradient():
  path = '/content/drive/My Drive/cutePic1.jpg'
  img = cv.imread(path, cv.IMREAD_GRAYSCALE)

  lapacian = cv.Laplacian(img, cv.CV_64F, ksize=21)

  plt.figure()
  plt.subplot(131)
  plt.imshow(lapacian, cmap = 'gray')

  kx, ky = cv.getDerivKernels(1, 0, 3)
  print(kx@ky.T)

  #more detail on X Axis
  sobelX = cv.Sobel(img, cv.CV_64F, 1, 0, ksize=21)
  plt.subplot(132)
  plt.imshow(sobelX, cmap = 'gray')
  plt.show()

  #more detail on Y Axis
  kx, ky = cv.getDerivKernels(0, 1, 3)
  sobelY = cv.Sobel(img, cv.CV_64F, 0, 1, ksize=21)
  plt.subplot(133)
  plt.imshow(sobelY, cmap = 'gray')
  plt.show()

if __name__ == '__main__':
  imageGradient()